/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoragesRouteImport } from './routes/storages'
import { Route as IndexRouteImport } from './routes/index'

const StoragesRoute = StoragesRouteImport.update({
  id: '/storages',
  path: '/storages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/storages': typeof StoragesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/storages': typeof StoragesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/storages': typeof StoragesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/storages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/storages'
  id: '__root__' | '/' | '/storages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoragesRoute: typeof StoragesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storages': {
      id: '/storages'
      path: '/storages'
      fullPath: '/storages'
      preLoaderRoute: typeof StoragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoragesRoute: StoragesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
